# Generated by Django 4.2 on 2023-11-02 15:53

import django.db.models.deletion
from django.db import migrations, models

import ottu.contrib.django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "session_id",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Session ID",
                    ),
                ),
                ("amount", models.CharField(max_length=20, verbose_name="Amount")),
                (
                    "attachment",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "attachment_short_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Attachment Short URL",
                    ),
                ),
                (
                    "billing_address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Billing Address",
                    ),
                ),
                (
                    "checkout_short_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Checkout Short URL",
                    ),
                ),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Checkout URL",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True,
                        max_length=250,
                        verbose_name="Customer Email",
                    ),
                ),
                (
                    "customer_first_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Customer First Name",
                    ),
                ),
                (
                    "customer_last_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Customer Last Name",
                    ),
                ),
                (
                    "customer_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Customer ID",
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Customer Phone",
                    ),
                ),
                (
                    "due_datetime",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Due Datetime",
                    ),
                ),
                (
                    "email_recipients",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Email Recipients",
                    ),
                ),
                (
                    "expiration_time",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Expiration Time",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="Extra"),
                ),
                (
                    "initiator_id",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Initiator ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "mode",
                    models.CharField(blank=True, max_length=250, verbose_name="Mode"),
                ),
                (
                    "notifications",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Notifications",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Operation",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Order No",
                    ),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=ottu.contrib.django.models.PaymentMethodEncoder,
                        verbose_name="Payment Methods",
                    ),
                ),
                (
                    "pg_codes",
                    models.JSONField(blank=True, default=dict, verbose_name="PG Codes"),
                ),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="QR Code URL",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Redirect URL",
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Shipping Address",
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=250, verbose_name="State"),
                ),
                (
                    "type",
                    models.CharField(blank=True, max_length=250, verbose_name="Type"),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="Vendor Name",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        max_length=250,
                        verbose_name="Webhook URL",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Checkout",
                "verbose_name_plural": "Checkout",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=250, verbose_name="Session ID"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ottu.checkout",
                        verbose_name="Checkout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "abstract": False,
            },
        ),
    ]
